[profile.default]
via-ir = true
optimizer_runs = 4294967295

[invariant]
runs = 16
depth = 256
fail_on_revert = true

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
