[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

[fuzz]
runs = 2048

[invariant]
runs = 2048
depth = 32

[fmt]
int_types = "short"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
