name: Certora

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install certora
        run: pip install certora-cli-beta

      - name: Install solc
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc8.19

      - name: Verify rule ${{ matrix.script }}
        run: |
          echo "key length" ${#CERTORAKEY}
          bash certora/scripts/${{ matrix.script }} --solc solc8.19
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

    strategy:
      fail-fast: false
      max-parallel: 4

      matrix:
        script:
          - verifyBlue.sh
          - verifyBlueAccrueInterests.sh
          - verifyBlueExitLiquidity.sh
          - verifyBlueLibSummary.sh
          - verifyBlueRatioMath.sh
          - verifyBlueReverts.sh
          - verifyBlueTransfer.sh
          - verifyDifficultMath.sh
          - verifyHealth.sh
          - verifyReentrancy.sh
